modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
    modId="daydreamer"
    version="${file.jarVersion}"
    displayName="Daydreamer"
    authors="joshiejack"
    description='''Allows you to sleep at any time of day, in order to skip to the next day.'''
[[dependencies.daydreamer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"